### ISSUE TITLE
Interrupts not working properly

### ISSUE THREAD

**Issue by ankitbhatia** [karu2003/MotorWare_eCAN#1]
I am trying to run the eCAN interrupts code for the F28069M processor. I am unable to trigger any receive interrupts. The transmit code works great. When I configure the mailboxes as shown in your example code I don't receive any interrupts:

```c
ECAN_configMailbox(handle->ecanaHandle, MailBox16, ECANIDS, Enable_Mbox, Rx_Dir, Standard_ID, DLC_8, Overwrite_off, LAMI_0, Mask_is_used, 0xFF80);
```
But when I change the configuration of the mailboxes to the one below, I am able to get interrupts but no data shows up (obviously, I need to send my messages with a message id of 0x010)
```c
ECAN_configMailbox(handle->ecanaHandle, MailBox16, 0x010, Enable_Mbox, Rx_Dir, Standard_ID, DLC_8, Overwrite_off, LAMI_0, Mask_not_used, 0xFF80);
```

Do you know what this issue could be? If needed I can give you more information about my setup.

**Comment by karu2003** [comment]
Which ID do you transfer? In my example ECANIDS = 6.

**Comment by ankitbhatia** [comment]
Ah thanks for pointing out that this only works with Hex ids ending with 6. It works now. It seems in your code the interrupt only triggers every 16 CAN messages. is there a way to have it trigger on every can message? I tried to setup the mailbox interrupt on every mailbox and it didn't work. Any suggestions?

**Comment by karu2003** [comment]
This is a feature of the C2000. It is necessary to reduce the number of mailbox. :(
ECAN_configMailbox_Int(halHandle->ecanaHandle, MailBox16, Int_enable, Line1);
